### ISSUE TITLE
manjaro linux install.sh error “libmemflow_daemon_connector.so not found“

### ISSUE THREAD

**Issue by cpkt9762** [memflow/cloudflow#14]
Updating git repository `https://github.com/h33p/minidump-writer`
  Downloaded anyhow v1.0.55
  Downloaded autocfg v1.1.0
  Downloaded bytes v1.1.0
  Downloaded chrono v0.4.19
  Downloaded clap v3.1.2
  Downloaded crossbeam-epoch v0.9.7
  Downloaded encoding-index-korean v1.20141219.5
  Downloaded encoding-index-tradchinese v1.20141219.5
  Downloaded encoding-index-japanese v1.20141219.5
  Downloaded async-trait v0.1.52
  Downloaded os_str_bytes v6.0.0
  Downloaded encoding_index_tests v0.1.4
  Downloaded chrono v0.2.25
  Downloaded encoding-index-simpchinese v1.20141219.5
  Downloaded getrandom v0.2.5
  Downloaded indexmap v1.8.0
  Downloaded textwrap v0.14.2
  Downloaded dashmap v5.1.0
  Downloaded num-iter v0.1.42
  Downloaded num-integer v0.1.44
  Downloaded num-rational v0.4.0
  Downloaded signal-hook-registry v1.4.0
  Downloaded memflow v0.2.0-beta3
  Downloaded num_cpus v1.13.1
  Downloaded time v0.1.43
  Downloaded pin-project-lite v0.2.8
  Downloaded num-traits v0.2.14
  Downloaded tokio v1.17.0
  Downloaded thread-scoped v1.0.2
  Downloaded threadpool v1.8.1
  Downloaded parking_lot_core v0.9.1
  Downloaded num-bigint v0.4.3
  Downloaded num v0.1.42
  Downloaded memoffset v0.6.5
  Downloaded parking_lot v0.12.0
  Downloaded semver v1.0.6
  Downloaded num-complex v0.4.0
  Downloaded sudo v0.6.0
  Downloaded range-map v0.1.5
  Downloaded pkg-config v0.3.24
  Downloaded num-traits v0.1.43
  Downloaded simplelog v0.11.2
  Downloaded tokio-macros v1.7.0
  Downloaded mio v0.8.0
  Downloaded socket2 v0.4.4
  Downloaded sharded-slab v0.1.4
  Downloaded minidump-common v0.1.0
  Downloaded fuse_mt v0.5.1
  Downloaded log v0.3.9
  Downloaded minidump v0.1.0
  Downloaded crossbeam-deque v0.8.1
  Downloaded proc-macro-crate v1.1.3
  Downloaded num v0.4.0
  Downloaded encoding-index-singlebyte v1.20141219.5
  Downloaded fuse v0.3.1
  Downloaded hashbrown v0.11.2
  Downloaded encoding v0.2.33
  Downloaded 57 crates (3.0 MB) in 2.31s
   Compiling libc v0.2.119
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.136
   Compiling serde_derive v1.0.136
   Compiling scopeguard v1.1.0
   Compiling log v0.4.14
   Compiling smallvec v1.8.0
   Compiling lazy_static v1.4.0
   Compiling core_extensions_proc_macros v1.5.1
   Compiling crossbeam-utils v0.8.7
   Compiling parking_lot_core v0.8.5
   Compiling once_cell v1.9.0
   Compiling tstr_proc_macros v0.2.2
   Compiling either v1.6.1
   Compiling parking_lot_core v0.9.1
   Compiling serde_json v1.0.79
   Compiling encoding_index_tests v0.1.4
   Compiling cfg-if v0.1.10
   Compiling itoa v1.0.1
   Compiling typed-arena v2.0.1
   Compiling ryu v1.0.9
   Compiling no-std-compat v0.4.1
   Compiling crossbeam-epoch v0.9.7
   Compiling paste v1.0.6
   Compiling ident_case v1.0.1
   Compiling version_check v0.9.4
   Compiling strsim v0.10.0
   Compiling fnv v1.0.7
   Compiling memchr v2.4.1
   Compiling bitflags v1.3.2
   Compiling pkg-config v0.3.24
   Compiling x86_64 v0.14.6
   Compiling dataview v0.1.2
   Compiling pelite-macros v0.1.1
   Compiling bit_field v0.10.1
   Compiling plain v0.2.3
   Compiling volatile v0.4.4
   Compiling thread-scoped v1.0.2
   Compiling bumpalo v3.9.1
   Compiling fixed-slice-vec v0.8.0
   Compiling rangemap v1.0.1
   Compiling anyhow v1.0.55
   Compiling termcolor v1.1.2
   Compiling hashbrown v0.11.2
   Compiling async-trait v0.1.52
   Compiling textwrap v0.14.2
   Compiling pin-project-lite v0.2.8
   Compiling bytes v1.1.0
   Compiling instant v0.1.12
   Compiling libloading v0.7.3
   Compiling lock_api v0.4.6
   Compiling sharded-slab v0.1.4
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling generational-arena v0.2.8
   Compiling itertools v0.10.3
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling memoffset v0.6.5
   Compiling num-iter v0.1.42
   Compiling num-bigint v0.4.3
   Compiling num-rational v0.4.0
   Compiling indexmap v1.8.0
   Compiling ahash v0.7.6
   Compiling tstr v0.2.2
   Compiling pelite v0.9.0
   Compiling encoding v0.2.33
   Compiling fuse v0.3.1
   Compiling log v0.3.9
   Compiling repr_offset v0.2.1
   Compiling crossbeam-channel v0.5.2
   Compiling core_extensions v1.5.2
   Compiling quote v1.0.15
   Compiling os_str_bytes v6.0.0
   Compiling time v0.1.43
   Compiling num_cpus v1.13.1
   Compiling getrandom v0.2.5
   Compiling dirs-sys v0.3.6
   Compiling minidump-common v0.1.0
   Compiling memmap v0.7.0
   Compiling coarsetime v0.1.21
   Compiling socket2 v0.4.4
   Compiling mio v0.8.0
   Compiling signal-hook-registry v1.4.0
   Compiling atty v0.2.14
   Compiling sudo v0.6.0
   Compiling abi_stable_shared v0.10.3
   Compiling crossbeam-deque v0.8.1
   Compiling threadpool v1.8.1
   Compiling parking_lot v0.11.2
   Compiling dirs v4.0.0
   Compiling parking_lot v0.12.0
   Compiling num-traits v0.1.43
   Compiling num-complex v0.4.0
   Compiling clap v3.1.2
   Compiling hashbrown v0.12.0
   Compiling dashmap v5.1.0
   Compiling range-map v0.1.5
   Compiling fuse_mt v0.5.1
   Compiling chrono v0.4.19
   Compiling num v0.1.42
   Compiling chrono v0.2.25
   Compiling minidump v0.1.0
   Compiling simplelog v0.11.2
   Compiling num v0.4.0
   Compiling as_derive_utils v0.10.3
   Compiling darling_core v0.13.1
   Compiling thiserror-impl v1.0.30
   Compiling abi_stable_derive v0.10.3
   Compiling scroll_derive v0.10.5
   Compiling tokio-macros v1.7.0
   Compiling darling_macro v0.13.1
   Compiling scroll v0.10.2
   Compiling tokio v1.17.0
   Compiling goblin v0.4.3
   Compiling minidump-writer v0.1.0 (https://github.com/h33p/minidump-writer#196c948b)
   Compiling darling v0.13.1
   Compiling thiserror v1.0.30
   Compiling toml v0.5.8
   Compiling abi_stable v0.10.4
   Compiling proc-macro-crate v1.1.3
   Compiling cglue-gen v0.2.4
   Compiling memflow-derive v0.2.0-beta2
   Compiling cglue-macro v0.2.2
   Compiling cglue v0.2.10
   Compiling filer v0.1.0 (/home/xch/vm/src/memflow/cloudflow/filer)
   Compiling memflow v0.2.0-beta3
warning: unused `std::result::Result` that must be used
   --> filer/src/node.rs:369:13
    |
369 |             self.0.close(self.1);
    |             ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled

   Compiling filer-fuse v0.1.0 (/home/xch/vm/src/memflow/cloudflow/filer-fuse)
   Compiling filer-tokio v0.1.0 (/home/xch/vm/src/memflow/cloudflow/filer-tokio)
warning: field is never read: `mount_point`
  --> filer-fuse/src/lib.rs:13:5
   |
13 |     mount_point: String,
   |     ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: unreachable expression
   --> filer-tokio/src/lib.rs:250:13
    |
201 | /             loop {
202 | |                 let mut idx = [0u8];
203 | |                 stream.read_exact(&mut idx).await?;
204 | |                 match idx[0] {
...   |
247 | |                 }
248 | |             }
    | |_____________- any code following this expression is unreachable
249 | 
250 |               Ok(())
    |               ^^^^^^ unreachable expression
    |
    = note: `#[warn(unreachable_code)]` on by default

warning: `filer` (lib) generated 1 warning
warning: `filer-fuse` (lib) generated 1 warning
warning: `filer-tokio` (lib) generated 1 warning
   Compiling cloudflow v0.1.0 (/home/xch/vm/src/memflow/cloudflow/cloudflow)
   Compiling cloudflow-minidump v0.1.0 (/home/xch/vm/src/memflow/cloudflow/cloudflow-minidump)
   Compiling cloudflow-node v0.1.0 (/home/xch/vm/src/memflow/cloudflow/cloudflow-node)
warning: unused import: `memflow::prelude::v1`
 --> cloudflow-node/src/main.rs:6:5
  |
6 | use memflow::prelude::v1::*;
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `cloudflow-node` (bin "cloudflow") generated 1 warning
    Finished release [optimized + debuginfo] target(s) in 45.79s
installing connector for user in ~/.local/lib/memflow
cp: 无法获取'target/release/libmemflow_daemon_connector.so' 的文件状态(stat): 没有那个文件或目录

**Comment by h33p** [comment]
Don't use `install.sh`, we should remove it.
